# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterFace_AddShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default='添加购物车', max_length=200)),
                ('login_result', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('return_value', models.CharField(max_length=200)),
                ('abnormal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterFace_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default='登录接口', max_length=200)),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('return_value', models.CharField(max_length=200)),
                ('abnormal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterFace_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default='搜索接口', max_length=200)),
                ('login_result', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('return_value', models.CharField(max_length=200)),
                ('abnormal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterFace_SubmitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default='提交订单接口', max_length=200)),
                ('login_result', models.CharField(max_length=100)),
                ('request_time', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('return_value', models.CharField(max_length=200)),
                ('abnormal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterFace_to_Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=200)),
                ('developerName', models.CharField(max_length=200)),
                ('LatestModifyDate', models.DateTimeField(auto_now=True)),
                ('editor', models.CharField(max_length=200)),
            ],
        ),
    ]
