# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-29 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mn_system', '0003_auto_20171229_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
    ]
