# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mn_system', '0006_auto_20180102_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacelist',
            name='abnormal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
