# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mn_system', '0007_auto_20180103_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacelist',
            name='return_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
